### model
model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z3_config.json  # choices: [ds_z0_config.json, ds_z2_config.json, ds_z3_config.json]

### dataset
dataset: stereoset_bias_full_sft
template: llama3
cutoff_len: 2048
max_samples: 10000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/debias/Llama-3.1-8B-Instruct/sft/task_vector
logging_steps: 10 
save_steps: 5
save_strategy: steps
save_total_limit: 1
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 35.0
lr_scheduler_type: cosine
warmup_ratio: 0.03
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.2
per_device_eval_batch_size: 8
eval_strategy: steps
eval_steps: 5
load_best_model_at_end: true

report_to: wandb
run_name: taskvector_sft_llama3.1-8b